# permissions for end users to edit commerces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commerce-editor-role
rules:
- apiGroups:
  - cache.commerce.k8sly.com
  resources:
  - commerces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.commerce.k8sly.com
  resources:
  - commerces/status
  verbs:
  - get
