# permissions for end users to view commerces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commerce-viewer-role
rules:
- apiGroups:
  - cache.commerce.k8sly.com
  resources:
  - commerces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.commerce.k8sly.com
  resources:
  - commerces/status
  verbs:
  - get
