
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - deployments
  - endpoints
  - events
  - namespaces
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - cache.commerce.k8scommerce.com
  resources:
  - commerces
  verbs:
  - '*'
- apiGroups:
  - cache.commerce.k8scommerce.com
  resources:
  - commerces/finalizers
  verbs:
  - update
- apiGroups:
  - cache.commerce.k8scommerce.com
  resources:
  - commerces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdbackups
  - etcdclusters
  - etcdrestores
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
