apiVersion: cache.commerce.k8sly.com/v1alpha1
kind: Commerce
metadata:
  name: commerce
  namespace: k8sly-system
spec:
  targetNamespace: k8sly-commerce
  corsOrigins:
    - http://local.k8sly.com:4200
    - http://localhost:4200

  hosts:
    client:
      hostname: api.local.k8sly.com
      scheme: "http"
    admin:
      hostname: admin.local.k8sly.com
      scheme: "http"

  database:
    secretName: k8sly-db-secret

  coreMicroServices:
    gatewayClient:
      name: gatewayclient
      image: localhost:5000/client:latest

    user:
      name: user
      image: localhost:5000/user:latest

    product:
      name: product
      image: localhost:5000/product:latest

    cart:
      name: cart
      image: localhost:5000/cart:latest

    inventory:
      name: inventory
      image: localhost:5000/inventory:latest

    othersBought:
      name: othersbought
      image: localhost:5000/othersbought:latest

    similarProducts:
      name: similarproducts
      image: localhost:5000/similarproducts:latest

  etcd:
    replicas: 0
