//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Commerce) DeepCopyInto(out *Commerce) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Commerce.
func (in *Commerce) DeepCopy() *Commerce {
	if in == nil {
		return nil
	}
	out := new(Commerce)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Commerce) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceCoreServices) DeepCopyInto(out *CommerceCoreServices) {
	*out = *in
	if in.GatewayClient != nil {
		in, out := &in.GatewayClient, &out.GatewayClient
		*out = new(CommerceService)
		(*in).DeepCopyInto(*out)
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(CommerceService)
		(*in).DeepCopyInto(*out)
	}
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(CommerceService)
		(*in).DeepCopyInto(*out)
	}
	if in.Cart != nil {
		in, out := &in.Cart, &out.Cart
		*out = new(CommerceService)
		(*in).DeepCopyInto(*out)
	}
	if in.Inventory != nil {
		in, out := &in.Inventory, &out.Inventory
		*out = new(CommerceService)
		(*in).DeepCopyInto(*out)
	}
	if in.OthersBought != nil {
		in, out := &in.OthersBought, &out.OthersBought
		*out = new(CommerceService)
		(*in).DeepCopyInto(*out)
	}
	if in.SimilarProducts != nil {
		in, out := &in.SimilarProducts, &out.SimilarProducts
		*out = new(CommerceService)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceCoreServices.
func (in *CommerceCoreServices) DeepCopy() *CommerceCoreServices {
	if in == nil {
		return nil
	}
	out := new(CommerceCoreServices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceDatabaseConnection) DeepCopyInto(out *CommerceDatabaseConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceDatabaseConnection.
func (in *CommerceDatabaseConnection) DeepCopy() *CommerceDatabaseConnection {
	if in == nil {
		return nil
	}
	out := new(CommerceDatabaseConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceEtcd) DeepCopyInto(out *CommerceEtcd) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceEtcd.
func (in *CommerceEtcd) DeepCopy() *CommerceEtcd {
	if in == nil {
		return nil
	}
	out := new(CommerceEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceHost) DeepCopyInto(out *CommerceHost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceHost.
func (in *CommerceHost) DeepCopy() *CommerceHost {
	if in == nil {
		return nil
	}
	out := new(CommerceHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceHosts) DeepCopyInto(out *CommerceHosts) {
	*out = *in
	out.Client = in.Client
	out.Admin = in.Admin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceHosts.
func (in *CommerceHosts) DeepCopy() *CommerceHosts {
	if in == nil {
		return nil
	}
	out := new(CommerceHosts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceList) DeepCopyInto(out *CommerceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Commerce, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceList.
func (in *CommerceList) DeepCopy() *CommerceList {
	if in == nil {
		return nil
	}
	out := new(CommerceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommerceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceResources) DeepCopyInto(out *CommerceResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceResources.
func (in *CommerceResources) DeepCopy() *CommerceResources {
	if in == nil {
		return nil
	}
	out := new(CommerceResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceService) DeepCopyInto(out *CommerceService) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnvironmentVars != nil {
		in, out := &in.EnvironmentVars, &out.EnvironmentVars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceService.
func (in *CommerceService) DeepCopy() *CommerceService {
	if in == nil {
		return nil
	}
	out := new(CommerceService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceSpec) DeepCopyInto(out *CommerceSpec) {
	*out = *in
	in.CoreServices.DeepCopyInto(&out.CoreServices)
	if in.AddOnServices != nil {
		in, out := &in.AddOnServices, &out.AddOnServices
		*out = make([]CommerceService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Hosts = in.Hosts
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(CommerceDatabaseConnection)
		**out = **in
	}
	in.Etcd.DeepCopyInto(&out.Etcd)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceSpec.
func (in *CommerceSpec) DeepCopy() *CommerceSpec {
	if in == nil {
		return nil
	}
	out := new(CommerceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceStatus) DeepCopyInto(out *CommerceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceStatus.
func (in *CommerceStatus) DeepCopy() *CommerceStatus {
	if in == nil {
		return nil
	}
	out := new(CommerceStatus)
	in.DeepCopyInto(out)
	return out
}
